### ISSUE TITLE
Logging issue when installed along with Restkit

### ISSUE THREAD

**Issue by sudhakarnataraj2224** [viki-org/VKVideoPlayer#25]
When I installed VKVideoPlayer through cocoapods few days back, I noticed that the logging function of the "Restkit" library was not working. To investigate, I uninstalled VKVideoPlayer form the pods. The logging of Restkit became normal and working. I don't know whether this is something related to CocoaLumberjack. Can you please look into this and give me a solution?

**Comment by jarrold** [comment]
Yes this seems like an issue with RestKit and CocoaLumberjack

https://github.com/RestKit/RestKit/issues/1393

Since there are a few issues regarding CocoaLumberjack, we might look into not using it.
