### ISSUE TITLE
Can't play Local Video.

### ISSUE THREAD

**Issue by Vishaliphone** [viki-org/VKVideoPlayer#26]
Hi,
Can i play Local Video with this player?
I have tried but it gives a blank screen.

Please do reply regarding this.

**Comment by romanvbabenko** [comment]
Yes, I can
I should create fileURL this ways

    NSURL *fileURL = [NSURL fileURLWithPath:filePathString];

instead of

   NSURL *fileURL = [NSURL URLWithString:filePathString];

**Comment by Vishaliphone** [comment]
Hi,
though I had already done this, i am unable to play video.

Please create your demo so people ca reach easily to it.
