### ISSUE TITLE
How to seek to last watched duration when user changed video quality ?

### ISSUE THREAD

**Issue by dproton** [viki-org/VKVideoPlayer#30]
Thank for your VK team because of creating this great library ?
Can you help me to solve a problem:
How to seek to last watched duration when user changed video quality ?

**Comment by jarrold** [comment]
what we do is to set the lastDurationWatchedInSeconds to the current time and reload the track with the new video quality.

**Comment by anphunl** [comment]
@jarrold 
Could you please explain more about your solution? 
I am using VKVideoPlayer via Pod in a project that use Swift. I can't set the value for current time because it has getter but no setter.

I tried to implement by use seek function like that but it didn't work, it played the new stream from beginning

var currentPlayTime = player.currentTime()
playVideoWithStreamURL(newStream)
self.player.seekToTimeInSecond(Float(currentPlayTime), userAction: true, completionHandler: nil)

Thank you very much,
Phu Nguyen

**Comment by vinoth56060** [comment]
@anphunl 
Can you tell me the solution for solve this issue?

**Comment by anphunl** [comment]
@vinoth56060 : first, I get the current play time, then switch to new video stream and seek to the saved time.

`long currentPlayTime = self.player.currentTime;
[self seekToTime:currentPlayTime];`

`-(void) seekToTime:(long)timeToSeek {
    dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
        while (self.player.state == VKVideoPlayerStateContentLoading) {
        }
        
        dispatch_async(dispatch_get_main_queue(), ^{
            [self.player seekToTimeInSecond:timeToSeek userAction:YES completionHandler:^(BOOL finished) {
                [self.player playContent];
            }];
        });
    });
}`

**Comment by vinoth56060** [comment]
@anphunl 
Its Working fine now thanks for the sample code, but whenever i changed the video quality starting page is visible for few seconds, is it possible to avoid that one, for your reference i attached sample screen shot.
![simulator screen shot 06-apr-2016 12 07 26 pm](https://cloud.githubusercontent.com/assets/11173902/14307924/4ecc5e76-fbf0-11e5-8fc6-1c2bb5ad53e3.png)

**Comment by anphunl** [comment]
@vinoth56060 : I met that problem too and I didn't find any solution for that. Actually, I moved to another libary, the Google Media Framework for android

**Comment by vinoth56060** [comment]
@anphunl 
Google Media Framework is available for iOS too?

**Comment by anphunl** [comment]
@vinoth56060 
Sorry, my mistake. I meant Google Media Framework for iOS. It's [here](https://github.com/googleads/google-media-framework-ios)
