### ISSUE TITLE
VKVideoPlayerView isControlsHidden and isControlsEnabled should be readonly

### ISSUE THREAD

**Issue by nicorsm** [viki-org/VKVideoPlayer#33]
Hi, I'm using playerControlsAutoHideTime property for hiding player controls in my app. But there are other two properties, isControlsHidden and isControlsEnabled, that are used internally but they're public and writeable. This can be confusing. If the properties aren't used for other features, you can leave them readonly.

**Comment by jarrold** [comment]
Hi @nicorsm thanks for this great suggestion. I'm sure there might be a few more of these.
