### ISSUE TITLE
Fail installing pod

### ISSUE THREAD

**Issue by jijijrey** [viki-org/VKVideoPlayer#34]
$ pod install
Analyzing dependencies

[!] The platform of the target `VKVideoPlayerTests` (iOS 5.0) is not compatible with `Expecta (0.3.2)` which has a minimum requirement of iOS 5.1.1 - OS X 10.7.

**Comment by praveenkumartapmobi** [comment]
Same issue am facing.

**Comment by liuqiyuan** [comment]
same here

**Comment by Lilacxyz** [comment]
Same issue, so how to solve it then?

**Comment by Lilacxyz** [comment]
I've deleted the test part in podfile and it runs well. XD Thanks any way.

**Comment by jarrold** [comment]
Yeah that would work too. :) We are re-evaluating if we are going to continue using Expecta.

**Comment by Lilacxyz** [comment]
That's a Matcher Framework? To tell the truth, I don't really understand what a Matcher Framework is used for. For example, why and how is it used in this project?
