### ISSUE TITLE
Video format VKVideoPlayer supported？

### ISSUE THREAD

**Issue by Lilacxyz** [viki-org/VKVideoPlayer#39]
I find it really useful to realize the video play function with this framework. But could you let me know which kind of video formats it supports? It will be really terrible if I've finished part of my project and have to change the video framework due to the format issue.....
Thanks in advance.

**Comment by jarrold** [comment]
Hi we use AVPlayer under the hood, you can see what kind of formats it can play from audiovisualMIMETypes I think
