### ISSUE TITLE
Unable to perform pod install command

### ISSUE THREAD

**Issue by idevmehra** [viki-org/VKVideoPlayer#47]
I try to install pod for  this lib's demo and getting this error.
Updating local specs repositories
Analyzing dependencies
Downloading dependencies
Installing AFNetworking (1.3.3)
Installing CocoaAsyncSocket (7.4.2)
Installing CocoaHTTPServer (2.3)
Installing CocoaLumberjack (1.7.0)
Installing DTCoreText (1.6.16)
Installing DTFoundation (1.7.7)
Installing Expecta (0.3.2)
Installing FXImageView (1.3.5)
Installing OCMock (2.2.4)
Installing Reachability (3.1.1)
Installing Specta (0.2.1)
Installing VKFoundation (0.1.1)
Generating Pods project
[!] An error occurred while processing the post-install hook of the Podfile.

undefined method `project' for #<Pod::Installer:0x007fd43a0bda18>

/Users/AjayMehra/Desktop/Aj Mehra/VKVideoPlayer-master/Podfile:17:in `block (2 levels) in from_ruby'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.38.2/lib/cocoapods-core/podfile.rb:170:in `call'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.38.2/lib/cocoapods-core/podfile.rb:170:in `post_install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:764:in `run_podfile_post_install_hook'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:752:in `block in run_podfile_post_install_hooks'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:140:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:751:in `run_podfile_post_install_hooks'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:155:in `block in generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:150:in `generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:110:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command.rb:48:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'

**Comment by n0n1** [comment]
@idevmehra you need change `project` to `pods_project`:

installer.pods_project.targets.each do |target|

**Comment by n0n1** [comment]
@idevmehra [more here](https://github.com/CocoaPods/CocoaPods/issues/3747)

**Comment by sahin** [comment]
check out https://github.com/mobileplayer/mobileplayer-ios
